// MOC header lists for Qt 6.8.3 static build
// Each entry is a header path relative to the module's source root.
// moc_*.cpp output name is derived: "subdir/qfoo.h" -> "moc_qfoo.cpp"
// .moc output name is derived: "subdir/qfoo.cpp" -> "qfoo.moc"

// ============================================================================
// QtCore (relative to qtbase/src/corelib/)
// ============================================================================

/// Headers that produce moc_*.cpp files (included via #include "moc_*.cpp" at end of source files)
pub const qtcore_moc_headers: []const []const u8 = &.{
    "animation/qabstractanimation.h",
    "animation/qabstractanimation_p.h",
    "animation/qanimationgroup.h",
    "animation/qparallelanimationgroup.h",
    "animation/qpauseanimation.h",
    "animation/qpropertyanimation.h",
    "animation/qsequentialanimationgroup.h",
    "animation/qvariantanimation.h",
    "io/qbuffer.h",
    "io/qfile.h",
    "io/qfiledevice.h",
    "io/qfileselector.h",
    "io/qfilesystemwatcher.h",
    "io/qfilesystemwatcher_p.h",
    "io/qfilesystemwatcher_polling_p.h",
    "io/qfilesystemwatcher_win_p.h",
    "io/qiodevice.h",
    "io/qnoncontiguousbytedevice_p.h",
    "io/qprocess.h",
    "io/qsavefile.h",
    "io/qsettings.h",
    "io/qstandardpaths.h",
    "io/qtemporaryfile.h",
    "io/qwindowspipereader_p.h",
    "io/qwindowspipewriter_p.h",
    "ipc/qsharedmemory.h",
    "ipc/qsystemsemaphore.h",
    "ipc/qtipccommon.h",
    "itemmodels/qabstractitemmodel.h",
    "itemmodels/qabstractproxymodel.h",
    "itemmodels/qconcatenatetablesproxymodel.h",
    "itemmodels/qidentityproxymodel.h",
    "itemmodels/qitemselectionmodel.h",
    "itemmodels/qsortfilterproxymodel.h",
    "itemmodels/qstringlistmodel.h",
    "itemmodels/qtransposeproxymodel.h",
    "kernel/qabstracteventdispatcher.h",
    "kernel/qchronotimer.h",
    "kernel/qcoreapplication.h",
    "kernel/qcoreevent.h",
    "kernel/qeventdispatcher_win_p.h",
    "kernel/qeventloop.h",
    "kernel/qmimedata.h",
    "kernel/qobject.h",
    "kernel/qobjectcleanuphandler.h",
    "kernel/qpermissions.h",
    "kernel/qsignalmapper.h",
    "kernel/qsingleshottimer_p.h",
    "kernel/qsocketnotifier.h",
    "kernel/qtimer.h",
    "kernel/qtranslator.h",
    "kernel/qwineventnotifier.h",
    "mimetypes/qmimetype.h",
    "plugin/qfactoryloader_p.h",
    "plugin/qlibrary.h",
    "plugin/qpluginloader.h",
    "serialization/qcborcommon.h",
    "serialization/qcborstreamreader.h",
    "serialization/qcborvalue.h",
    "serialization/qtextstream_p.h",
    "text/qlocale.h",
    "thread/qfuturewatcher.h",
    "thread/qthread.h",
    "thread/qthreadpool.h",
    "time/qcalendar.h",
    "tools/qcryptographichash.h",
    "tools/qeasingcurve.h",
    "tools/qtimeline.h",
};

/// .cpp sources that produce .moc files (relative to qtbase/src/corelib/)
pub const qtcore_moc_sources: []const []const u8 = &.{
    "itemmodels/qabstractitemmodel.cpp",
    "io/qfilesystemwatcher_win.cpp",
    "thread/qfutureinterface.cpp",
    "thread/qthreadpool.cpp",
};

/// Standalone headers: compiled as separate translation units (relative to qtbase/src/corelib/)
pub const qtcore_moc_standalone: []const []const u8 = &.{
    "global/qnamespace.h",
};

// ============================================================================
// QtGui (relative to qtbase/src/gui/)
// ============================================================================

pub const qtgui_moc_headers: []const []const u8 = &.{
    "accessible/qaccessible_base.h",
    "accessible/qaccessiblebridge.h",
    "accessible/qaccessiblecache_p.h",
    "accessible/qaccessibleplugin.h",
    "image/qiconengineplugin.h",
    "image/qimage.h",
    "image/qimageiohandler.h",
    "image/qmovie.h",
    "itemmodels/qfileinfogatherer_p.h",
    "itemmodels/qfilesystemmodel.h",
    "itemmodels/qstandarditemmodel.h",
    "kernel/qaction.h",
    "kernel/qactiongroup.h",
    "kernel/qclipboard.h",
    "kernel/qdnd_p.h",
    "kernel/qdrag.h",
    "kernel/qevent.h",
    "kernel/qeventpoint.h",
    "kernel/qgenericplugin.h",
    "kernel/qguiapplication.h",
    "kernel/qhighdpiscaling_p.h",
    "kernel/qinputdevice.h",
    "kernel/qinputdevicemanager_p.h",
    "kernel/qinputmethod.h",
    "kernel/qinternalmimedata_p.h",
    "kernel/qkeymapper_p.h",
    "kernel/qkeysequence.h",
    "kernel/qoffscreensurface.h",
    "kernel/qpaintdevicewindow.h",
    "kernel/qpalette.h",
    "kernel/qplatformdialoghelper.h",
    "kernel/qplatformgraphicsbuffer.h",
    "kernel/qplatforminputcontext.h",
    "kernel/qplatforminputcontextplugin_p.h",
    "kernel/qplatformintegrationplugin.h",
    "kernel/qplatformmenu.h",
    "kernel/qplatformnativeinterface.h",
    "kernel/qplatformscreen.h",
    "kernel/qplatformservices.h",
    "kernel/qplatformsharedgraphicscache.h",
    "kernel/qplatformsystemtrayicon.h",
    "kernel/qplatformtheme.h",
    "kernel/qplatformthemeplugin.h",
    "kernel/qpointingdevice.h",
    "kernel/qrasterwindow.h",
    "kernel/qscreen.h",
    "kernel/qsessionmanager.h",
    "kernel/qshapedpixmapdndwindow_p.h",
    "kernel/qshortcut.h",
    "kernel/qstylehints.h",
    "kernel/qsurface.h",
    "kernel/qsurfaceformat.h",
    "kernel/qwindow.h",
    "painting/qbrush.h",
    "painting/qcolorspace.h",
    "painting/qpainter.h",
    "painting/qpdfwriter.h",
    "painting/qplatformbackingstore.h",
    "platform/windows/qwindowsguieventdispatcher_p.h",
    "text/qabstracttextdocumentlayout.h",
    "text/qfont.h",
    "text/qfontdatabase.h",
    "text/qinputcontrol_p.h",
    "text/qsyntaxhighlighter.h",
    "text/qtextdocument.h",
    "text/qtextdocumentlayout_p.h",
    "text/qtextformat.h",
    "text/qtextimagehandler_p.h",
    "text/qtextlist.h",
    "text/qtextobject.h",
    "text/qtexttable.h",
    "util/qlayoutpolicy_p.h",
    "util/qundogroup.h",
    "util/qundostack.h",
    "util/qvalidator.h",
};

pub const qtgui_moc_sources: []const []const u8 = &.{
    "image/qpixmapcache.cpp",
};

// Empty file stubs: headers that need an empty moc output (e.g., OpenGL disabled)
pub const qtgui_moc_empty: []const []const u8 = &.{
    "moc_qopenglcontext.cpp",
};

// ============================================================================
// QtWidgets (relative to qtbase/src/widgets/)
// ============================================================================

pub const qtwidgets_moc_headers: []const []const u8 = &.{
    "dialogs/qcolordialog.h",
    "dialogs/qdialog.h",
    "dialogs/qerrormessage.h",
    "dialogs/qfiledialog.h",
    "dialogs/qfontdialog.h",
    "dialogs/qinputdialog.h",
    "dialogs/qmessagebox.h",
    "dialogs/qprogressdialog.h",
    "dialogs/qsidebar_p.h",
    "dialogs/qwizard.h",
    "effects/qgraphicseffect.h",
    "effects/qgraphicseffect_p.h",
    "effects/qpixmapfilter_p.h",
    "graphicsview/qgraphicsanchorlayout.h",
    "graphicsview/qgraphicsitem.h",
    "graphicsview/qgraphicsitemanimation.h",
    "graphicsview/qgraphicsproxywidget.h",
    "graphicsview/qgraphicsscene.h",
    "graphicsview/qgraphicsscenebsptreeindex_p.h",
    "graphicsview/qgraphicssceneindex_p.h",
    "graphicsview/qgraphicsscenelinearindex_p.h",
    "graphicsview/qgraphicstransform.h",
    "graphicsview/qgraphicsview.h",
    "graphicsview/qgraphicswidget.h",
    "itemviews/qabstractitemdelegate.h",
    "itemviews/qabstractitemview.h",
    "itemviews/qcolumnview.h",
    "itemviews/qcolumnviewgrip_p.h",
    "itemviews/qdatawidgetmapper.h",
    "itemviews/qheaderview.h",
    "itemviews/qitemdelegate.h",
    "itemviews/qitemeditorfactory_p.h",
    "itemviews/qlistview.h",
    "itemviews/qlistwidget.h",
    "itemviews/qlistwidget_p.h",
    "itemviews/qstyleditemdelegate.h",
    "itemviews/qtableview.h",
    "itemviews/qtablewidget.h",
    "itemviews/qtablewidget_p.h",
    "itemviews/qtreeview.h",
    "itemviews/qtreewidget.h",
    "itemviews/qtreewidget_p.h",
    "kernel/qapplication.h",
    "kernel/qboxlayout.h",
    "kernel/qformlayout.h",
    "kernel/qgesture.h",
    "kernel/qgesturemanager_p.h",
    "kernel/qgridlayout.h",
    "kernel/qlayout.h",
    "kernel/qrhiwidget.h",
    "kernel/qsizepolicy.h",
    "kernel/qstackedlayout.h",
    "kernel/qwidget.h",
    "kernel/qwidget_p.h",
    "kernel/qwidgetaction.h",
    "kernel/qwidgetrepaintmanager_p.h",
    "kernel/qwidgetwindow_p.h",
    "kernel/qwindowcontainer_p.h",
    "styles/qcommonstyle.h",
    "styles/qfusionstyle_p.h",
    "styles/qpixmapstyle_p.h",
    "styles/qproxystyle.h",
    "styles/qstyle.h",
    "styles/qstyleanimation_p.h",
    "styles/qstyleplugin.h",
    "styles/qstylesheetstyle_p.h",
    "styles/qwindowsstyle_p.h",
    "util/qcompleter.h",
    "util/qcompleter_p.h",
    "util/qflickgesture_p.h",
    "util/qscroller.h",
    "util/qscroller_p.h",
    "util/qsystemtrayicon.h",
    "util/qsystemtrayicon_p.h",
    "util/qundoview.h",
    "widgets/qabstractbutton.h",
    "widgets/qabstractscrollarea.h",
    "widgets/qabstractscrollarea_p.h",
    "widgets/qabstractslider.h",
    "widgets/qabstractspinbox.h",
    "widgets/qbuttongroup.h",
    "widgets/qcalendarwidget.h",
    "widgets/qcheckbox.h",
    "widgets/qcombobox.h",
    "widgets/qcombobox_p.h",
    "widgets/qcommandlinkbutton.h",
    "widgets/qdatetimeedit.h",
    "widgets/qdatetimeedit_p.h",
    "widgets/qdial.h",
    "widgets/qdialogbuttonbox.h",
    "widgets/qdockwidget.h",
    "widgets/qdockwidget_p.h",
    "widgets/qfocusframe.h",
    "widgets/qfontcombobox.h",
    "widgets/qframe.h",
    "widgets/qgroupbox.h",
    "widgets/qkeysequenceedit.h",
    "widgets/qlabel.h",
    "widgets/qlcdnumber.h",
    "widgets/qlineedit.h",
    "widgets/qlineedit_p.h",
    "widgets/qmainwindow.h",
    "widgets/qmainwindowlayout_p.h",
    "widgets/qmdiarea.h",
    "widgets/qmdisubwindow.h",
    "widgets/qmenu.h",
    "widgets/qmenubar.h",
    "widgets/qplaintextedit.h",
    "widgets/qplaintextedit_p.h",
    "widgets/qprogressbar.h",
    "widgets/qpushbutton.h",
    "widgets/qradiobutton.h",
    "widgets/qrubberband.h",
    "widgets/qscrollarea.h",
    "widgets/qscrollbar.h",
    "widgets/qsizegrip.h",
    "widgets/qslider.h",
    "widgets/qspinbox.h",
    "widgets/qsplashscreen.h",
    "widgets/qsplitter.h",
    "widgets/qstackedwidget.h",
    "widgets/qstatusbar.h",
    "widgets/qtabbar.h",
    "widgets/qtabwidget.h",
    "widgets/qtextbrowser.h",
    "widgets/qtextedit.h",
    "widgets/qtoolbar.h",
    "widgets/qtoolbarextension_p.h",
    "widgets/qtoolbarlayout_p.h",
    "widgets/qtoolbarseparator_p.h",
    "widgets/qtoolbox.h",
    "widgets/qtoolbutton.h",
    "widgets/qwidgetanimator_p.h",
    "widgets/qwidgetlinecontrol_p.h",
    "widgets/qwidgetresizehandler_p.h",
    "widgets/qwidgettextcontrol_p.h",
};

pub const qtwidgets_moc_sources: []const []const u8 = &.{
    "widgets/qcalendarwidget.cpp",
    "dialogs/qcolordialog.cpp",
    "widgets/qdockwidget.cpp",
    "widgets/qeffects.cpp",
    "widgets/qfontcombobox.cpp",
    "dialogs/qfontdialog.cpp",
    "dialogs/qinputdialog.cpp",
    "itemviews/qitemeditorfactory.cpp",
    "itemviews/qlistwidget.cpp",
    "widgets/qmainwindowlayout.cpp",
    "widgets/qmdisubwindow.cpp",
    "widgets/qmenu.cpp",
    "dialogs/qmessagebox.cpp",
    "widgets/qtabbar.cpp",
    "itemviews/qtableview.cpp",
    "widgets/qtoolbox.cpp",
    "kernel/qtooltip.cpp",
    "util/qundoview.cpp",
    "kernel/qwhatsthis.cpp",
    "kernel/qwidgetrepaintmanager.cpp",
};

// ============================================================================
// QtNetwork (relative to qtbase/src/network/)
// ============================================================================

pub const qtnetwork_moc_headers: []const []const u8 = &.{
    "access/qabstractnetworkcache.h",
    "access/qhttp2connection_p.h",
    "access/qhttp2protocolhandler_p.h",
    "access/qhttpheaders.h",
    "access/qhttpmultipart.h",
    "access/qhttpnetworkconnection_p.h",
    "access/qhttpnetworkconnectionchannel_p.h",
    "access/qhttpnetworkreply_p.h",
    "access/qhttpthreaddelegate_p.h",
    "access/qnetworkaccessbackend_p.h",
    "access/qnetworkaccesscache_p.h",
    "access/qnetworkaccessfilebackend_p.h",
    "access/qnetworkaccessmanager.h",
    "access/qnetworkcookie.h",
    "access/qnetworkcookiejar.h",
    "access/qnetworkdiskcache.h",
    "access/qnetworkfile_p.h",
    "access/qnetworkreply.h",
    "access/qnetworkreplydataimpl_p.h",
    "access/qnetworkreplyfileimpl_p.h",
    "access/qnetworkreplyhttpimpl_p.h",
    "access/qnetworkreplyimpl_p.h",
    "access/qnetworkrequest.h",
    "access/qrestaccessmanager.h",
    "kernel/qauthenticator.h",
    "kernel/qdnslookup.h",
    "kernel/qdnslookup_p.h",
    "kernel/qhostaddress.h",
    "kernel/qhostinfo.h",
    "kernel/qhostinfo_p.h",
    "kernel/qnetconmonitor_p.h",
    "kernel/qnetworkinformation.h",
    "kernel/qnetworkinformation_p.h",
    "kernel/qnetworkinterface.h",
    "kernel/qnetworkproxy.h",
    "socket/qabstractsocket.h",
    "socket/qabstractsocketengine_p.h",
    "socket/qhttpsocketengine_p.h",
    "socket/qlocalserver.h",
    "socket/qlocalsocket.h",
    "socket/qnativesocketengine_p.h",
    "socket/qsocks5socketengine_p.h",
    "socket/qtcpserver.h",
    "socket/qtcpsocket.h",
    "socket/qudpsocket.h",
    "ssl/qssl.h",
    "ssl/qsslerror.h",
    "ssl/qsslpresharedkeyauthenticator.h",
    "ssl/qsslserver.h",
    "ssl/qsslsocket.h",
    "ssl/qtlsbackend_p.h",
};

pub const qtnetwork_moc_sources: []const []const u8 = &.{
    "kernel/qnetworkinformation.cpp",
};

// ============================================================================
// qwindows platform plugin (relative to qtbase/src/plugins/platforms/windows/)
// ============================================================================

/// Standalone headers: compiled as separate translation units
pub const qwindows_moc_standalone: []const []const u8 = &.{
    "qwindowsgdinativeinterface.h",
    "qwindowsinputcontext.h",
    "qwindowsmenu.h",
    "qwindowsnativeinterface.h",
    "uiautomation/qwindowsuiabaseprovider.h",
    "uiautomation/qwindowsuiamainprovider.h",
    "uiautomation/qwindowsuiaprovidercache.h",
};

pub const qwindows_moc_sources: []const []const u8 = &.{
    "main.cpp",
    "qwindowsdialoghelpers.cpp",
};
