// Additional source file lists for Qt 6.8.3 static build with Zig
// Generated from Qt source tree analysis
// Target: Windows x86_64

// ============================================================================
// HarfBuzz-NG sources (relative to qtbase/src/3rdparty/harfbuzz-ng/)
// ============================================================================

pub const harfbuzz_sources: []const []const u8 = &.{
    // Parent directory
    "hb-dummy.cc",
    // src/ directory
    "src/hb-aat-layout.cc",
    "src/hb-aat-map.cc",
    "src/hb-blob.cc",
    "src/hb-buffer.cc",
    "src/hb-buffer-serialize.cc",
    "src/hb-buffer-verify.cc",
    "src/hb-common.cc",
    "src/hb-draw.cc",
    "src/hb-face.cc",
    "src/hb-face-builder.cc",
    "src/hb-fallback-shape.cc",
    "src/hb-font.cc",
    "src/hb-map.cc",
    "src/hb-number.cc",
    "src/hb-ot-cff1-table.cc",
    "src/hb-ot-cff2-table.cc",
    "src/hb-ot-color.cc",
    "src/hb-ot-face.cc",
    "src/hb-ot-font.cc",
    "src/hb-ot-layout.cc",
    "src/hb-ot-map.cc",
    "src/hb-ot-math.cc",
    "src/hb-ot-meta.cc",
    "src/hb-ot-metrics.cc",
    "src/hb-ot-name.cc",
    "src/hb-ot-shape.cc",
    "src/hb-ot-shape-fallback.cc",
    "src/hb-ot-shape-normalize.cc",
    "src/hb-ot-shaper-arabic.cc",
    "src/hb-ot-shaper-default.cc",
    "src/hb-ot-shaper-hangul.cc",
    "src/hb-ot-shaper-hebrew.cc",
    "src/hb-ot-shaper-indic.cc",
    "src/hb-ot-shaper-indic-table.cc",
    "src/hb-ot-shaper-khmer.cc",
    "src/hb-ot-shaper-myanmar.cc",
    "src/hb-ot-shaper-syllabic.cc",
    "src/hb-ot-shaper-thai.cc",
    "src/hb-ot-shaper-use.cc",
    "src/hb-ot-shaper-vowel-constraints.cc",
    "src/hb-ot-tag.cc",
    "src/hb-ot-var.cc",
    "src/hb-outline.cc",
    "src/hb-paint.cc",
    "src/hb-paint-extents.cc",
    "src/hb-set.cc",
    "src/hb-shape.cc",
    "src/hb-shape-plan.cc",
    "src/hb-shaper.cc",
    "src/hb-static.cc",
    "src/hb-style.cc",
    "src/hb-subset.cc",
    "src/hb-subset-cff-common.cc",
    "src/hb-subset-cff1.cc",
    "src/hb-subset-cff2.cc",
    "src/hb-subset-input.cc",
    "src/hb-subset-instancer-iup.cc",
    "src/hb-subset-instancer-solver.cc",
    "src/hb-subset-plan.cc",
    "src/hb-subset-serialize.cc",
    "src/hb-ucd.cc",
    "src/hb-unicode.cc",
    "src/OT/Var/VARC/VARC.cc",
};

// ============================================================================
// FreeType 2 sources (amalgamated build, relative to qtbase/src/3rdparty/freetype/)
// ============================================================================

pub const freetype_sources: []const []const u8 = &.{
    "src/autofit/autofit.c",
    "src/base/ftbase.c",
    "src/base/ftbbox.c",
    "src/base/ftbdf.c",
    "src/base/ftbitmap.c",
    "src/base/ftcid.c",
    "src/base/ftfstype.c",
    "src/base/ftgasp.c",
    "src/base/ftglyph.c",
    "src/base/ftgxval.c",
    "src/base/ftinit.c",
    "src/base/ftmm.c",
    "src/base/ftotval.c",
    "src/base/ftpatent.c",
    "src/base/ftpfr.c",
    "src/base/ftstroke.c",
    "src/base/ftsynth.c",
    "src/base/ftsystem.c",
    "src/base/fttype1.c",
    "src/base/ftwinfnt.c",
    "src/bdf/bdf.c",
    "src/bzip2/ftbzip2.c",
    "src/cache/ftcache.c",
    "src/cff/cff.c",
    "src/cid/type1cid.c",
    "src/gzip/ftgzip.c",
    "src/lzw/ftlzw.c",
    "src/pcf/pcf.c",
    "src/pfr/pfr.c",
    "src/psaux/psaux.c",
    "src/pshinter/pshinter.c",
    "src/psnames/psnames.c",
    "src/raster/raster.c",
    "src/sdf/sdf.c",
    "src/sfnt/sfnt.c",
    "src/smooth/smooth.c",
    "src/svg/svg.c",
    "src/truetype/truetype.c",
    "src/type1/type1.c",
    "src/type42/type42.c",
    "src/winfonts/winfnt.c",
    // Windows-specific
    "builds/windows/ftdebug.c",
};

// ============================================================================
// libpng sources (relative to qtbase/src/3rdparty/libpng/)
// ============================================================================

pub const libpng_sources: []const []const u8 = &.{
    "png.c",
    "pngerror.c",
    "pngget.c",
    "pngmem.c",
    "pngpread.c",
    "pngread.c",
    "pngrio.c",
    "pngrtran.c",
    "pngrutil.c",
    "pngset.c",
    "pngtrans.c",
    "pngwio.c",
    "pngwrite.c",
    "pngwtran.c",
    "pngwutil.c",
};

// ============================================================================
// libjpeg-turbo sources (relative to qtbase/src/3rdparty/libjpeg/)
// ============================================================================

pub const libjpeg_sources: []const []const u8 = &.{
    "src/jaricom.c",
    "src/jcapimin.c",
    "src/jcapistd.c",
    "src/jcarith.c",
    "src/jccoefct.c",
    "src/jccolor.c",
    "src/jcdctmgr.c",
    "src/jcdiffct.c",
    "src/jchuff.c",
    "src/jcicc.c",
    "src/jcinit.c",
    "src/jclhuff.c",
    "src/jclossls.c",
    "src/jcmainct.c",
    "src/jcmarker.c",
    "src/jcmaster.c",
    "src/jcomapi.c",
    "src/jcparam.c",
    "src/jcphuff.c",
    "src/jcprepct.c",
    "src/jcsample.c",
    "src/jctrans.c",
    "src/jdapimin.c",
    "src/jdapistd.c",
    "src/jdarith.c",
    "src/jdatadst.c",
    "src/jdatasrc.c",
    "src/jdcoefct.c",
    "src/jdcolor.c",
    "src/jddctmgr.c",
    "src/jddiffct.c",
    "src/jdhuff.c",
    "src/jdicc.c",
    "src/jdinput.c",
    "src/jdlhuff.c",
    "src/jdlossls.c",
    "src/jdmainct.c",
    "src/jdmarker.c",
    "src/jdmaster.c",
    "src/jdmerge.c",
    "src/jdphuff.c",
    "src/jdpostct.c",
    "src/jdsample.c",
    "src/jdtrans.c",
    "src/jerror.c",
    "src/jfdctflt.c",
    "src/jfdctfst.c",
    "src/jfdctint.c",
    "src/jidctflt.c",
    "src/jidctfst.c",
    "src/jidctint.c",
    "src/jidctred.c",
    "src/jmemmgr.c",
    "src/jmemnobs.c",
    "src/jpeg_nbits.c",
    "src/jquant1.c",
    "src/jquant2.c",
    "src/jutils.c",
};

// ============================================================================
// QtGui common (cross-platform) sources (relative to qtbase/src/gui/)
// ============================================================================

pub const qtgui_common_sources: []const []const u8 = &.{
    // accessible
    "accessible/qaccessible.cpp",
    "accessible/qaccessiblebridge.cpp",
    "accessible/qaccessiblebridgeutils.cpp",
    "accessible/qaccessiblecache.cpp",
    "accessible/qaccessibleobject.cpp",
    "accessible/qaccessibleplugin.cpp",
    "accessible/qplatformaccessibility.cpp",
    // animation
    "animation/qguivariantanimation.cpp",
    // compat
    "compat/removed_api.cpp",
    // image
    "image/qabstractfileiconengine.cpp",
    "image/qabstractfileiconprovider.cpp",
    "image/qbitmap.cpp",
    "image/qbmphandler.cpp",
    "image/qicon.cpp",
    "image/qiconengine.cpp",
    "image/qiconengineplugin.cpp",
    "image/qiconloader.cpp",
    "image/qimage.cpp",
    "image/qimage_conversions.cpp",
    "image/qimageiohandler.cpp",
    "image/qimagepixmapcleanuphooks.cpp",
    "image/qimagereader.cpp",
    "image/qimagereaderwriterhelpers.cpp",
    "image/qimagewriter.cpp",
    "image/qmovie.cpp",
    "image/qpaintengine_pic.cpp",
    "image/qpicture.cpp",
    "image/qpixmap.cpp",
    "image/qpixmap_blitter.cpp",
    "image/qpixmap_raster.cpp",
    "image/qpixmapcache.cpp",
    "image/qplatformpixmap.cpp",
    "image/qpnghandler.cpp",
    "image/qppmhandler.cpp",
    "image/qxbmhandler.cpp",
    "image/qxpmhandler.cpp",
    // itemmodels
    "itemmodels/qfileinfogatherer.cpp",
    "itemmodels/qfilesystemmodel.cpp",
    "itemmodels/qstandarditemmodel.cpp",
    // kernel
    "kernel/qaction.cpp",
    "kernel/qactiongroup.cpp",
    "kernel/qclipboard.cpp",
    "kernel/qcursor.cpp",
    "kernel/qdnd.cpp",
    "kernel/qdrag.cpp",
    "kernel/qevent.cpp",
    "kernel/qeventpoint.cpp",
    "kernel/qgenericplugin.cpp",
    "kernel/qgenericpluginfactory.cpp",
    "kernel/qguiapplication.cpp",
    "kernel/qguivariant.cpp",
    "kernel/qhighdpiscaling.cpp",
    "kernel/qinputdevice.cpp",
    "kernel/qinputdevicemanager.cpp",
    "kernel/qinputmethod.cpp",
    "kernel/qinternalmimedata.cpp",
    "kernel/qkeymapper.cpp",
    "kernel/qkeysequence.cpp",
    "kernel/qoffscreensurface.cpp",
    "kernel/qpaintdevicewindow.cpp",
    "kernel/qpalette.cpp",
    "kernel/qpixelformat.cpp",
    "kernel/qplatformclipboard.cpp",
    "kernel/qplatformcursor.cpp",
    "kernel/qplatformdialoghelper.cpp",
    "kernel/qplatformdrag.cpp",
    "kernel/qplatformgraphicsbuffer.cpp",
    "kernel/qplatformgraphicsbufferhelper.cpp",
    "kernel/qplatforminputcontext.cpp",
    "kernel/qplatforminputcontextfactory.cpp",
    "kernel/qplatforminputcontextplugin.cpp",
    "kernel/qplatformintegration.cpp",
    "kernel/qplatformintegrationfactory.cpp",
    "kernel/qplatformintegrationplugin.cpp",
    "kernel/qplatformkeymapper.cpp",
    "kernel/qplatformmenu.cpp",
    "kernel/qplatformnativeinterface.cpp",
    "kernel/qplatformoffscreensurface.cpp",
    "kernel/qplatformscreen.cpp",
    "kernel/qplatformservices.cpp",
    "kernel/qplatformsessionmanager.cpp",
    "kernel/qplatformsharedgraphicscache.cpp",
    "kernel/qplatformsurface.cpp",
    "kernel/qplatformsystemtrayicon.cpp",
    "kernel/qplatformtheme.cpp",
    "kernel/qplatformthemefactory.cpp",
    "kernel/qplatformthemeplugin.cpp",
    "kernel/qplatformwindow.cpp",
    "kernel/qpointingdevice.cpp",
    "kernel/qrasterwindow.cpp",
    "kernel/qscreen.cpp",
    "kernel/qsessionmanager.cpp",
    "kernel/qshapedpixmapdndwindow.cpp",
    "kernel/qshortcut.cpp",
    "kernel/qshortcutmap.cpp",
    "kernel/qsimpledrag.cpp",
    "kernel/qstylehints.cpp",
    "kernel/qsurface.cpp",
    "kernel/qsurfaceformat.cpp",
    "kernel/qtestsupport_gui.cpp",
    "kernel/qwindow.cpp",
    "kernel/qwindowsysteminterface.cpp",
    // math3d
    "math3d/qgenericmatrix.cpp",
    "math3d/qmatrix4x4.cpp",
    "math3d/qquaternion.cpp",
    "math3d/qvectornd.cpp",
    // painting (excluding SIMD-specific files)
    "painting/qbackingstore.cpp",
    "painting/qbackingstoredefaultcompositor.cpp",
    "painting/qbackingstorerhisupport.cpp",
    "painting/qbezier.cpp",
    "painting/qblendfunctions.cpp",
    "painting/qblittable.cpp",
    "painting/qbrush.cpp",
    "painting/qcolor.cpp",
    "painting/qcolorspace.cpp",
    "painting/qcolortransform.cpp",
    "painting/qcolortrclut.cpp",
    "painting/qcompositionfunctions.cpp",
    "painting/qcosmeticstroker.cpp",
    "painting/qcssutil.cpp",
    "painting/qdrawhelper.cpp",
    "painting/qemulationpaintengine.cpp",
    "painting/qicc.cpp",
    "painting/qimageeffects.cpp",
    "painting/qimagescale.cpp",
    "painting/qmemrotate.cpp",
    "painting/qoutlinemapper.cpp",
    "painting/qpagedpaintdevice.cpp",
    "painting/qpagelayout.cpp",
    "painting/qpageranges.cpp",
    "painting/qpagesize.cpp",
    "painting/qpaintdevice.cpp",
    "painting/qpaintengine.cpp",
    "painting/qpaintengine_blitter.cpp",
    "painting/qpaintengine_raster.cpp",
    "painting/qpaintengineex.cpp",
    "painting/qpainter.cpp",
    "painting/qpainterpath.cpp",
    "painting/qpathclipper.cpp",
    "painting/qpathsimplifier.cpp",
    "painting/qpdf.cpp",
    "painting/qpdfoutputintent.cpp",
    "painting/qpdfwriter.cpp",
    "painting/qpen.cpp",
    "painting/qpixellayout.cpp",
    "painting/qplatformbackingstore.cpp",
    "painting/qpolygon.cpp",
    "painting/qrasterizer.cpp",
    "painting/qregion.cpp",
    "painting/qstroker.cpp",
    "painting/qtextureglyphcache.cpp",
    "painting/qtransform.cpp",
    "painting/qtriangulatingstroker.cpp",
    "painting/qtriangulator.cpp",
    // rhi (common only)
    "rhi/qrhi.cpp",
    "rhi/qrhinull.cpp",
    "rhi/qshader.cpp",
    "rhi/qshaderdescription.cpp",
    // text (common, excluding platform-specific subdirs)
    "text/qabstracttextdocumentlayout.cpp",
    "text/qcssparser.cpp",
    "text/qdistancefield.cpp",
    "text/qfont.cpp",
    "text/qfontdatabase.cpp",
    "text/qfontengine.cpp",
    "text/qfontengineglyphcache.cpp",
    "text/qfontmetrics.cpp",
    "text/qfontsubset.cpp",
    "text/qfontsubset_agl.cpp",
    "text/qfragmentmap.cpp",
    "text/qglyphrun.cpp",
    "text/qharfbuzzng.cpp",
    "text/qinputcontrol.cpp",
    "text/qplatformfontdatabase.cpp",
    "text/qrawfont.cpp",
    "text/qstatictext.cpp",
    "text/qsyntaxhighlighter.cpp",
    "text/qtextcursor.cpp",
    "text/qtextdocument.cpp",
    "text/qtextdocument_p.cpp",
    "text/qtextdocumentfragment.cpp",
    "text/qtextdocumentlayout.cpp",
    "text/qtextdocumentwriter.cpp",
    "text/qtextengine.cpp",
    "text/qtextformat.cpp",
    "text/qtexthtmlparser.cpp",
    "text/qtextimagehandler.cpp",
    "text/qtextlayout.cpp",
    "text/qtextlist.cpp",
    "text/qtextmarkdownimporter.cpp",
    "text/qtextmarkdownwriter.cpp",
    "text/qtextobject.cpp",
    "text/qtextodfwriter.cpp",
    "text/qtextoption.cpp",
    "text/qtexttable.cpp",
    // util
    "util/qabstractlayoutstyleinfo.cpp",
    "util/qastchandler.cpp",
    "util/qdesktopservices.cpp",
    "util/qedidparser.cpp",
    "util/qgridlayoutengine.cpp",
    "util/qktxhandler.cpp",
    "util/qlayoutpolicy.cpp",
    "util/qpkmhandler.cpp",
    "util/qtexturefiledata.cpp",
    "util/qtexturefilereader.cpp",
    "util/qundogroup.cpp",
    "util/qundostack.cpp",
    "util/qvalidator.cpp",
};

// QtGui C sources (need separate compilation as C)
pub const qtgui_c_sources: []const []const u8 = &.{
    "painting/qgrayraster.c",
};

// QtGui SIMD-specific sources (need special compiler flags)
pub const qtgui_sse2_sources: []const []const u8 = &.{
    "painting/qdrawhelper_sse2.cpp",
};

pub const qtgui_ssse3_sources: []const []const u8 = &.{
    "painting/qdrawhelper_ssse3.cpp",
    "image/qimage_ssse3.cpp",
};

pub const qtgui_sse4_sources: []const []const u8 = &.{
    "painting/qdrawhelper_sse4.cpp",
    "painting/qimagescale_sse4.cpp",
};

pub const qtgui_avx2_sources: []const []const u8 = &.{
    "painting/qdrawhelper_avx2.cpp",
};

// ============================================================================
// QtGui Windows-specific sources (relative to qtbase/src/gui/)
// ============================================================================

pub const qtgui_win_sources: []const []const u8 = &.{
    "platform/windows/qwindowsguieventdispatcher.cpp",
    "platform/windows/qwindowsmimeconverter.cpp",
    "platform/windows/qwindowsnativeinterface.cpp",
    "platform/windows/qwindowsthemecache.cpp",
    "text/windows/qwindowsfontdatabase.cpp",
    "text/windows/qwindowsfontdatabasebase.cpp",
    "text/windows/qwindowsfontengine.cpp",
    "text/windows/qwindowsnativeimage.cpp",
    "text/windows/qwindowsfontenginedirectwrite.cpp",
    "text/windows/qwindowsdirectwritefontdatabase.cpp",
    "text/windows/qwindowsfontdatabase_ft.cpp",
    "image/qpixmap_win.cpp",
    "rhi/qrhid3d11.cpp",
    "rhi/qrhid3d12.cpp",
    "rhi/qrhid3dhelpers.cpp",
};

// ============================================================================
// QtGui FreeType text engine sources (relative to qtbase/src/gui/)
// ============================================================================

pub const qtgui_freetype_sources: []const []const u8 = &.{
    "text/freetype/qfontengine_ft.cpp",
    "text/freetype/qfreetypefontdatabase.cpp",
};

// ============================================================================
// QtWidgets common (cross-platform) sources (relative to qtbase/src/widgets/)
// ============================================================================

pub const qtwidgets_common_sources: []const []const u8 = &.{
    // accessible
    "accessible/complexwidgets.cpp",
    "accessible/itemviews.cpp",
    "accessible/qaccessiblemenu.cpp",
    "accessible/qaccessiblewidget.cpp",
    "accessible/qaccessiblewidgetfactory.cpp",
    "accessible/qaccessiblewidgets.cpp",
    "accessible/rangecontrols.cpp",
    "accessible/simplewidgets.cpp",
    // compat
    "compat/removed_api.cpp",
    // dialogs
    "dialogs/qcolordialog.cpp",
    "dialogs/qdialog.cpp",
    "dialogs/qerrormessage.cpp",
    "dialogs/qfiledialog.cpp",
    "dialogs/qfontdialog.cpp",
    "dialogs/qinputdialog.cpp",
    "dialogs/qmessagebox.cpp",
    "dialogs/qprogressdialog.cpp",
    "dialogs/qsidebar.cpp",
    "dialogs/qwizard.cpp",
    // effects
    "effects/qgraphicseffect.cpp",
    "effects/qpixmapfilter.cpp",
    // graphicsview
    "graphicsview/qgraphicsanchorlayout.cpp",
    "graphicsview/qgraphicsanchorlayout_p.cpp",
    "graphicsview/qgraphicsgridlayout.cpp",
    "graphicsview/qgraphicsgridlayoutengine.cpp",
    "graphicsview/qgraphicsitem.cpp",
    "graphicsview/qgraphicsitemanimation.cpp",
    "graphicsview/qgraphicslayout.cpp",
    "graphicsview/qgraphicslayout_p.cpp",
    "graphicsview/qgraphicslayoutitem.cpp",
    "graphicsview/qgraphicslayoutstyleinfo.cpp",
    "graphicsview/qgraphicslinearlayout.cpp",
    "graphicsview/qgraphicsproxywidget.cpp",
    "graphicsview/qgraphicsscene.cpp",
    "graphicsview/qgraphicsscene_bsp.cpp",
    "graphicsview/qgraphicsscenebsptreeindex.cpp",
    "graphicsview/qgraphicssceneevent.cpp",
    "graphicsview/qgraphicssceneindex.cpp",
    "graphicsview/qgraphicsscenelinearindex.cpp",
    "graphicsview/qgraphicstransform.cpp",
    "graphicsview/qgraphicsview.cpp",
    "graphicsview/qgraphicswidget.cpp",
    "graphicsview/qgraphicswidget_p.cpp",
    "graphicsview/qsimplex_p.cpp",
    // itemviews
    "itemviews/qabstractitemdelegate.cpp",
    "itemviews/qabstractitemview.cpp",
    "itemviews/qbsptree.cpp",
    "itemviews/qcolumnview.cpp",
    "itemviews/qcolumnviewgrip.cpp",
    "itemviews/qdatawidgetmapper.cpp",
    "itemviews/qfileiconprovider.cpp",
    "itemviews/qheaderview.cpp",
    "itemviews/qitemdelegate.cpp",
    "itemviews/qitemeditorfactory.cpp",
    "itemviews/qlistview.cpp",
    "itemviews/qlistwidget.cpp",
    "itemviews/qstyleditemdelegate.cpp",
    "itemviews/qtableview.cpp",
    "itemviews/qtablewidget.cpp",
    "itemviews/qtreeview.cpp",
    "itemviews/qtreewidget.cpp",
    "itemviews/qtreewidgetitemiterator.cpp",
    // kernel
    "kernel/qaction_widgets.cpp",
    "kernel/qapplication.cpp",
    "kernel/qboxlayout.cpp",
    "kernel/qformlayout.cpp",
    "kernel/qgesture.cpp",
    "kernel/qgesturemanager.cpp",
    "kernel/qgesturerecognizer.cpp",
    "kernel/qgridlayout.cpp",
    "kernel/qlayout.cpp",
    "kernel/qlayoutengine.cpp",
    "kernel/qlayoutitem.cpp",
    "kernel/qrhiwidget.cpp",
    "kernel/qshortcut_widgets.cpp",
    "kernel/qsizepolicy.cpp",
    "kernel/qstackedlayout.cpp",
    "kernel/qstandardgestures.cpp",
    "kernel/qtestsupport_widgets.cpp",
    "kernel/qtooltip.cpp",
    "kernel/qwhatsthis.cpp",
    "kernel/qwidget.cpp",
    "kernel/qwidgetaction.cpp",
    "kernel/qwidgetrepaintmanager.cpp",
    "kernel/qwidgetsvariant.cpp",
    "kernel/qwidgetwindow.cpp",
    "kernel/qwindowcontainer.cpp",
    // styles
    "styles/qcommonstyle.cpp",
    "styles/qdrawutil.cpp",
    "styles/qfusionstyle.cpp",
    "styles/qpixmapstyle.cpp",
    "styles/qproxystyle.cpp",
    "styles/qstyle.cpp",
    "styles/qstyleanimation.cpp",
    "styles/qstylefactory.cpp",
    "styles/qstylehelper.cpp",
    "styles/qstyleoption.cpp",
    "styles/qstylepainter.cpp",
    "styles/qstyleplugin.cpp",
    "styles/qstylesheetstyle.cpp",
    "styles/qstylesheetstyle_default.cpp",
    "styles/qwindowsstyle.cpp",
    // util
    "util/qcolormap.cpp",
    "util/qcompleter.cpp",
    "util/qflickgesture.cpp",
    "util/qscroller.cpp",
    "util/qscrollerproperties.cpp",
    "util/qsystemtrayicon.cpp",
    "util/qsystemtrayicon_qpa.cpp",
    "util/qundoview.cpp",
    // widgets
    "widgets/qabstractbutton.cpp",
    "widgets/qabstractscrollarea.cpp",
    "widgets/qabstractslider.cpp",
    "widgets/qabstractspinbox.cpp",
    "widgets/qbuttongroup.cpp",
    "widgets/qcalendarwidget.cpp",
    "widgets/qcheckbox.cpp",
    "widgets/qcombobox.cpp",
    "widgets/qcommandlinkbutton.cpp",
    "widgets/qdatetimeedit.cpp",
    "widgets/qdial.cpp",
    "widgets/qdialogbuttonbox.cpp",
    "widgets/qdockarealayout.cpp",
    "widgets/qdockwidget.cpp",
    "widgets/qeffects.cpp",
    "widgets/qfocusframe.cpp",
    "widgets/qfontcombobox.cpp",
    "widgets/qframe.cpp",
    "widgets/qgroupbox.cpp",
    "widgets/qkeysequenceedit.cpp",
    "widgets/qlabel.cpp",
    "widgets/qlcdnumber.cpp",
    "widgets/qlineedit.cpp",
    "widgets/qlineedit_p.cpp",
    "widgets/qmainwindow.cpp",
    "widgets/qmainwindowlayout.cpp",
    "widgets/qmdiarea.cpp",
    "widgets/qmdisubwindow.cpp",
    "widgets/qmenu.cpp",
    "widgets/qmenubar.cpp",
    "widgets/qplaintextedit.cpp",
    "widgets/qprogressbar.cpp",
    "widgets/qpushbutton.cpp",
    "widgets/qradiobutton.cpp",
    "widgets/qrubberband.cpp",
    "widgets/qscrollarea.cpp",
    "widgets/qscrollbar.cpp",
    "widgets/qsizegrip.cpp",
    "widgets/qslider.cpp",
    "widgets/qspinbox.cpp",
    "widgets/qsplashscreen.cpp",
    "widgets/qsplitter.cpp",
    "widgets/qstackedwidget.cpp",
    "widgets/qstatusbar.cpp",
    "widgets/qtabbar.cpp",
    "widgets/qtabwidget.cpp",
    "widgets/qtextbrowser.cpp",
    "widgets/qtextedit.cpp",
    "widgets/qtoolbar.cpp",
    "widgets/qtoolbararealayout.cpp",
    "widgets/qtoolbarextension.cpp",
    "widgets/qtoolbarlayout.cpp",
    "widgets/qtoolbarseparator.cpp",
    "widgets/qtoolbox.cpp",
    "widgets/qtoolbutton.cpp",
    "widgets/qwidgetanimator.cpp",
    "widgets/qwidgetlinecontrol.cpp",
    "widgets/qwidgetresizehandler.cpp",
    "widgets/qwidgettextcontrol.cpp",
};

// ============================================================================
// QtWidgets Windows-specific sources (relative to qtbase/src/widgets/)
// ============================================================================

pub const qtwidgets_win_sources: []const []const u8 = &.{
    "dialogs/qwizard_win.cpp",
};

// ============================================================================
// QtNetwork common (cross-platform) sources (relative to qtbase/src/network/)
// ============================================================================

pub const qtnetwork_common_sources: []const []const u8 = &.{
    // access
    "access/http2/bitstreams.cpp",
    "access/http2/hpack.cpp",
    "access/http2/hpacktable.cpp",
    "access/http2/http2frames.cpp",
    "access/http2/http2protocol.cpp",
    "access/http2/http2streams.cpp",
    "access/http2/huffman.cpp",
    "access/qabstractnetworkcache.cpp",
    "access/qabstractprotocolhandler.cpp",
    "access/qdecompresshelper.cpp",
    "access/qformdatabuilder.cpp",
    "access/qhsts.cpp",
    "access/qhstspolicy.cpp",
    "access/qhstsstore.cpp",
    "access/qhttp1configuration.cpp",
    "access/qhttp2configuration.cpp",
    "access/qhttp2connection.cpp",
    "access/qhttp2protocolhandler.cpp",
    "access/qhttpheaderparser.cpp",
    "access/qhttpheaders.cpp",
    "access/qhttpheadershelper.cpp",
    "access/qhttpmultipart.cpp",
    "access/qhttpnetworkconnection.cpp",
    "access/qhttpnetworkconnectionchannel.cpp",
    "access/qhttpnetworkheader.cpp",
    "access/qhttpnetworkreply.cpp",
    "access/qhttpnetworkrequest.cpp",
    "access/qhttpprotocolhandler.cpp",
    "access/qhttpthreaddelegate.cpp",
    "access/qnetworkaccessauthenticationmanager.cpp",
    "access/qnetworkaccessbackend.cpp",
    "access/qnetworkaccesscache.cpp",
    "access/qnetworkaccesscachebackend.cpp",
    "access/qnetworkaccessfilebackend.cpp",
    "access/qnetworkaccessmanager.cpp",
    "access/qnetworkcookie.cpp",
    "access/qnetworkcookiejar.cpp",
    "access/qnetworkdiskcache.cpp",
    "access/qnetworkfile.cpp",
    "access/qnetworkreply.cpp",
    "access/qnetworkreplydataimpl.cpp",
    "access/qnetworkreplyfileimpl.cpp",
    "access/qnetworkreplyhttpimpl.cpp",
    "access/qnetworkreplyimpl.cpp",
    "access/qnetworkrequest.cpp",
    "access/qnetworkrequestfactory.cpp",
    "access/qrestaccessmanager.cpp",
    "access/qrestreply.cpp",
    // compat
    "compat/removed_api.cpp",
    // kernel
    "kernel/qauthenticator.cpp",
    "kernel/qdnslookup.cpp",
    "kernel/qhostaddress.cpp",
    "kernel/qhostinfo.cpp",
    "kernel/qnetworkdatagram.cpp",
    "kernel/qnetworkinformation.cpp",
    "kernel/qnetworkinterface.cpp",
    "kernel/qnetworkproxy.cpp",
    // socket
    "socket/qabstractsocket.cpp",
    "socket/qabstractsocketengine.cpp",
    "socket/qhttpsocketengine.cpp",
    "socket/qlocalserver.cpp",
    "socket/qlocalsocket.cpp",
    "socket/qnativesocketengine.cpp",
    "socket/qsocks5socketengine.cpp",
    "socket/qtcpserver.cpp",
    "socket/qtcpsocket.cpp",
    "socket/qudpsocket.cpp",
    // ssl
    "ssl/qocspresponse.cpp",
    "ssl/qpassworddigestor.cpp",
    "ssl/qssl.cpp",
    "ssl/qsslcertificate.cpp",
    "ssl/qsslcertificateextension.cpp",
    "ssl/qsslcipher.cpp",
    "ssl/qsslconfiguration.cpp",
    "ssl/qssldiffiehellmanparameters.cpp",
    "ssl/qsslellipticcurve.cpp",
    "ssl/qsslerror.cpp",
    "ssl/qsslkey_p.cpp",
    "ssl/qsslpresharedkeyauthenticator.cpp",
    "ssl/qsslserver.cpp",
    "ssl/qsslsocket.cpp",
    "ssl/qtlsbackend.cpp",
};

// ============================================================================
// QtNetwork Windows-specific sources (relative to qtbase/src/network/)
// ============================================================================

pub const qtnetwork_win_sources: []const []const u8 = &.{
    "kernel/qhostinfo_win.cpp",
    "kernel/qnetworkinterface_win.cpp",
    "kernel/qnetworkproxy_win.cpp",
    "kernel/qdnslookup_win.cpp",
    "kernel/qnetconmonitor_win.cpp",
    "socket/qnativesocketengine_win.cpp",
    "socket/qlocalserver_win.cpp",
    "socket/qlocalsocket_win.cpp",
};

// ============================================================================
// QtConcurrent sources (relative to qtbase/src/concurrent/)
// ============================================================================

pub const qtconcurrent_sources: []const []const u8 = &.{
    "qtconcurrentfilter.cpp",
    "qtconcurrentiteratekernel.cpp",
    "qtconcurrentmap.cpp",
    "qtconcurrentrun.cpp",
    "qtconcurrentthreadengine.cpp",
};

// ============================================================================
// QWindows platform plugin sources (relative to qtbase/src/plugins/platforms/windows/)
// ============================================================================

pub const qwindows_plugin_sources: []const []const u8 = &.{
    "main.cpp",
    "qwin10helpers.cpp",
    "qwindowsapplication.cpp",
    "qwindowsbackingstore.cpp",
    "qwindowsclipboard.cpp",
    "qwindowscontext.cpp",
    "qwindowscursor.cpp",
    "qwindowsdialoghelpers.cpp",
    "qwindowsdrag.cpp",
    "qwindowsdropdataobject.cpp",
    "qwindowsgdiintegration.cpp",
    "qwindowsgdinativeinterface.cpp",
    "qwindowsiconengine.cpp",
    "qwindowsinputcontext.cpp",
    "qwindowsintegration.cpp",
    "qwindowsinternalmimedata.cpp",
    "qwindowskeymapper.cpp",
    "qwindowsmenu.cpp",
    "qwindowsmimeregistry.cpp",
    "qwindowsnativeinterface.cpp",
    "qwindowsole.cpp",
    "qwindowspointerhandler.cpp",
    "qwindowsscreen.cpp",
    "qwindowsservices.cpp",
    "qwindowssessionmanager.cpp",
    "qwindowssystemtrayicon.cpp",
    "qwindowstabletsupport.cpp",
    "qwindowstheme.cpp",
    "qwindowswindow.cpp",
    // uiautomation
    "uiautomation/qwindowsuiaaccessibility.cpp",
    "uiautomation/qwindowsuiabaseprovider.cpp",
    "uiautomation/qwindowsuiaexpandcollapseprovider.cpp",
    "uiautomation/qwindowsuiagriditemprovider.cpp",
    "uiautomation/qwindowsuiagridprovider.cpp",
    "uiautomation/qwindowsuiainvokeprovider.cpp",
    "uiautomation/qwindowsuiamainprovider.cpp",
    "uiautomation/qwindowsuiaprovidercache.cpp",
    "uiautomation/qwindowsuiarangevalueprovider.cpp",
    "uiautomation/qwindowsuiaselectionitemprovider.cpp",
    "uiautomation/qwindowsuiaselectionprovider.cpp",
    "uiautomation/qwindowsuiatableitemprovider.cpp",
    "uiautomation/qwindowsuiatableprovider.cpp",
    "uiautomation/qwindowsuiatextprovider.cpp",
    "uiautomation/qwindowsuiatextrangeprovider.cpp",
    "uiautomation/qwindowsuiatoggleprovider.cpp",
    "uiautomation/qwindowsuiautils.cpp",
    "uiautomation/qwindowsuiautomation.cpp",
    "uiautomation/qwindowsuiavalueprovider.cpp",
    "uiautomation/qwindowsuiawindowprovider.cpp",
    "qwindowsopengltester.cpp",
};
